### ISSUE TITLE
Changing adapter throws an exception

### ISSUE THREAD

**Issue by frost13it** [orhanobut/simplelistview#4]
When I trying to change adapter of SimpleListview like this:

```
    final ArrayAdapter<String> adapter1 =
            new ArrayAdapter<>(context, android.R.layout.simple_list_item_1);
    final ArrayAdapter<String> adapter2 =
            new ArrayAdapter<>(context, android.R.layout.simple_list_item_1);
    simpleListView.setAdapter(adapter1);
    simpleListView.setAdapter(adapter2);
```

An exception is thrown:

```
java.lang.IllegalStateException: Observer com.orhanobut.simplelistview.SimpleListView$AdapterDataSetObserver@4199dbf0 was not registered.
at android.database.Observable.unregisterObserver(Observable.java:69)
at android.widget.BaseAdapter.unregisterDataSetObserver(BaseAdapter.java:42)
at com.orhanobut.simplelistview.SimpleListView.setAdapter(SimpleListView.java:94)
```

**Comment by orhanobut** [comment]
thank you! I'll check this issue.

**Comment by orhanobut** [comment]
or any PR is more than welcome
